### ISSUE TITLE
Toolchain and libraries for BedRock NOVA?

### ISSUE THREAD

**Issue by lonnietc** [bedrocksystems/vml#1]
Hello,

I am highly interested in using your NOVA kernel (https://github.com/bedrocksystems/NOVA) with your VML libraries to compile for the x86_64 platform and was wondering if you also have the toolchain and needed libraries to built for it available as the current VML libraries seem to be missing a number of components as well as refer to:

BRS_ROOT ?= ../../zeta/

throughout the Makefiles.

Is there some what that I can get the all of the libraries need to build this wonderful combination of NOVA and VML so that I cam start building some software to contribute back?

Thanks in advance

**Comment by julienfreche** [comment]
Hello Ionnietc,

Thanks for your question and interest. Unfortunately, we do not provide open-source versions of those apps and libraries at the moment.

Best,

**Comment by lonnietc** [comment]
Thanks again for you response and I will seek other options.

Have a great weekend.
